### ISSUE TITLE
Fehler beim Aufruf von dbench init -h und dbench init --dbname postgres --username postgres --host 127.0.0.1 --port 5433

### ISSUE THREAD

**Issue by thomasksr** [nikoksr/dbench#1]
@nikoksr 
Beim Aufruf von 
"dbench init -h" 
oder  
"dbench init --dbname postgres --username postgres --host 127.0.0.1 --port 5433" kommt die folgenden Meldung
panic: unable to redefine 'h' shorthand in "init" flagset: it's already used for "host" flag

Hier noch die Scrrens dazu

![Fehler](https://github.com/nikoksr/dbench/assets/48161297/dc0237f5-2613-4877-b88c-392d07a38ae9)

![Pfad](https://github.com/nikoksr/dbench/assets/48161297/cd272091-976b-4f0b-a75e-39c2d19b46da)

**Comment by nikoksr** [comment]
Fixed in 0ced9685651926adcd4b7dcceda51e370f3c9421.
