### ISSUE TITLE
Der Export dbench export funktioniert nicht mehr

### ISSUE THREAD

**Issue by thomasksr** [nikoksr/dbench#16]
### What happened (or didn't happen) and how can we reproduce the problem?

@nikoksr 
Die dbench.db hat eine Größe von 118KB
Wenn ich diese mit dem Befehl dbench export ausgeben möchte werden keine Daten ausgeben. Außer der Header wird in der csv angeigt.
![2023-11-24_12h10_03](https://github.com/nikoksr/dbench/assets/48161297/5e099e88-ca27-4452-a941-5ec520236b8a)

### dbench doctor

```bash
dbench 0.11.0
─────────────

Checking dbench database...
  Connecting ... ✓ Success

Checking required tools...
  pgbench ... ✓ Found (13.13 (Debian 13.13-0+deb11u1))
  gnuplot ... ✓ Found (5.4 patchlevel 1)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nikoksr** [comment]
Kann ich nicht nachstellen, @thomasksr. Kann mir nur vorstellen, dass das was mit dem System zu tun hat. Ist das die selbe Maschine, die #11 ausgelöst hat?

Edit:

`dbench doctor` auf meiner Maschine:

```bash     
dbench 0.11.0
─────────────
             
Checking dbench database...
  Connecting ... ✓ Success

Checking required tools...
  pgbench ... ✓ Found (15.4)
  gnuplot ... ✓ Found (5.4 patchlevel 10)
  ```

**Comment by thomasksr** [comment]
@nikoksr , ja, ist die gleich Debian VM

**Comment by nikoksr** [comment]
Fixed in #17
